
Commit message suggestion: `Add README`

---

# 2) _config.yml (site/theme settings)

**Where:** root → “Add file → Create new file” → name it `_config.yml`

```yaml
# --- Site configuration for GitHub Pages (Jekyll) ---
title: Sara Maknojia Portfolio
description: Data Analyst | SQL + Python | MSDS Candidate @ BU
url: "https://saramaknojia94-ux.github.io"

# Theme
theme: jekyll-theme-cayman

# Build options
markdown: kramdown
kramdown:
  input: GFM

# (Optional) social links for the footer or future use
linkedin_url: "https://www.linkedin.com/in/sara-maknojia"
github_url: "https://github.com/saramaknojia94-ux"
resume_url: "/assets/Sara_Maknojia_Resume.pdf"
